name: PyRight

on: [ pull_request, push ]

jobs:
  build:
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyRight & Dependencies
        run: |
          pip install -U poetry pyright
          pip install --no-dev

      - name: Run PyRight
        run: pyright ./
